### PR TITLE
updated example app

### PR DESCRIPTION
**Pull request by Harshit933**
Updated the UI of the example app.

### CODE REVIEW

**Comment by Harshit933** [comment]
fixes #154

**Comment by ricardobrg** [comment]
@Harshit933 could you please add a screenshot of the screen here? This way we can do a visual validation and compare it with the original design in the issue.

**Comment by Harshit933** [comment]
Sure here it is:

Screenshot_20230223_124559

**Comment by ricardobrg** [comment]
This example app will be moved to the TIKI examples repository. This PR will be recreated in the new repository.

**Pull request closed without merging**
